apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app }}
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          resources:
            limits:
              cpu: {{ .Values.limits.cpu }}
              memory: {{ .Values.limits.memory }}
            requests:
              cpu: {{ .Values.requests.cpu }}
              memory: {{ .Values.requests.memory }}

          ports:
            - containerPort: {{ .Values.service.port }}
          
          volumeMounts: 
            - mountPath: {{ .Values.volumeMounts.mountPath }}
              name: {{ .Values.volumeMounts.name }}

      volumes: 
         - name: {{ .Values.volumes.name }}
           emptyDir: {}


