{{- if .Values.nexus.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.nexus.ingress.name }}
  namespace: {{ .Values.namespace }}

spec:
  rules:
  - host: {{ .Values.nexus.ingress.hosts.host }}
    http:
      paths: {{- range .Values.nexus.ingress.hosts.paths }}
        - path: /
          pathType: Prefix
          backend:
            serviceName: {{ .service.name }}
            servicePort: {{ .service.port }}
        {{- end }}
{{- end }}


